In [93]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [94]:
df = pd.read_csv('bdt_mba_supplychain_dataset_2024.csv')
df.head()

,Asset_ID,Location,Temperature,Vibration,Last_Maintenance,Condition_Score,Resource_Utilization,Delivery_Efficiency,Downtime_Hours,Inventory_Level,Logistics_Cost,Timestamp,SupplyChain_Efficiency_Label
0,A0001,Lake Davidland,32.34,3.99,2023-09-28,67.39,87.04,79.99,3.22,Medium,5148.45,2024-09-13 19:31:26,0
1,A0002,West Andrew,25.99,0.80,2023-04-26,76.44,81.06,92.07,2.89,Low,4454.82,2023-09-17 22:20:17,1
2,A0003,New Kimberlyhaven,31.45,4.75,2024-12-23,61.85,79.64,88.15,1.65,High,3977.16,2024-09-08 19:32:27,1
3,A0004,Lake Cathyside,26.55,4.37,2024-10-22,63.60,79.88,72.63,8.07,Low,3248.65,2023-10-28 06:48:55,0
4,A0005,South Justin,41.66,1.43,2024-08-17,61.62,65.99,74.93,1.83,High,3121.08,2023-10-06 05:02:02,0

In [95]:
df.shape

(500, 13)

In [96]:
df.columns

Index(['Asset_ID', 'Location', 'Temperature', 'Vibration', 'Last_Maintenance',
       'Condition_Score', 'Resource_Utilization', 'Delivery_Efficiency',
       'Downtime_Hours', 'Inventory_Level', 'Logistics_Cost', 'Timestamp',
       'SupplyChain_Efficiency_Label'],
      dtype='str')

In [97]:
df.dtypes

Asset_ID                            str
Location                            str
Temperature                     float64
Vibration                       float64
Last_Maintenance                    str
Condition_Score                 float64
Resource_Utilization            float64
Delivery_Efficiency             float64
Downtime_Hours                  float64
Inventory_Level                     str
Logistics_Cost                  float64
Timestamp                           str
SupplyChain_Efficiency_Label      int64
dtype: object

In [98]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 13 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Asset_ID                      500 non-null    str
 1   Location                      500 non-null    str
 2   Temperature                   500 non-null    float64
 3   Vibration                     500 non-null    float64
 4   Last_Maintenance              500 non-null    str
 5   Condition_Score               500 non-null    float64
 6   Resource_Utilization          500 non-null    float64
 7   Delivery_Efficiency           500 non-null    float64
 8   Downtime_Hours                500 non-null    float64
 9   Inventory_Level               500 non-null    str
 10  Logistics_Cost                500 non-null    float64
 11  Timestamp                     500 non-null    str
 12  SupplyChain_Efficiency_Label  500 non-null    int64
dtypes: float64(7), int64(1), str(5)
memory usage: 50.9 KB

In [99]:
df.describe()

,Temperature,Vibration,Condition_Score,Resource_Utilization,Delivery_Efficiency,Downtime_Hours,Logistics_Cost,SupplyChain_Efficiency_Label
count,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000
mean,34.691180,2.508240,74.878440,77.879940,84.165620,5.025020,4973.418100,0.506000
std,8.791835,1.470361,14.134638,10.075504,8.077746,2.961775,1183.049596,0.542727
min,20.080000,0.000000,50.010000,60.010000,70.020000,0.020000,3000.760000,0.000000
25%,26.687500,1.187500,62.687500,69.300000,77.080000,2.540000,4048.407500,0.000000
50%,34.575000,2.480000,74.780000,78.555000,84.595000,5.050000,4777.445000,0.000000
75%,42.275000,3.790000,87.357500,86.315000,90.665000,7.682500,6075.320000,1.000000
max,49.880000,4.990000,99.970000,94.960000,97.980000,10.000000,6999.180000,2.000000

In [100]:
df.isnull()

,Asset_ID,Location,Temperature,Vibration,Last_Maintenance,Condition_Score,Resource_Utilization,Delivery_Efficiency,Downtime_Hours,Inventory_Level,Logistics_Cost,Timestamp,SupplyChain_Efficiency_Label
0,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,False,False,False,False,False,False,False,False,False,False,False,False,False
496,False,False,False,False,False,False,False,False,False,False,False,False,False
497,False,False,False,False,False,False,False,False,False,False,False,False,False
498,False,False,False,False,False,False,False,False,False,False,False,False,False
499,False,False,False,False,False,False,False,False,False,False,False,False,False

In [101]:
df.isnull().sum()

Asset_ID                        0
Location                        0
Temperature                     0
Vibration                       0
Last_Maintenance                0
Condition_Score                 0
Resource_Utilization            0
Delivery_Efficiency             0
Downtime_Hours                  0
Inventory_Level                 0
Logistics_Cost                  0
Timestamp                       0
SupplyChain_Efficiency_Label    0
dtype: int64

In [102]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
495    False
496    False
497    False
498    False
499    False
Length: 500, dtype: bool

In [103]:
df.duplicated().sum()

np.int64(0)

In [104]:
df['Location'].duplicated().sum()

np.int64(12)

In [105]:
df.nunique()

Asset_ID                        500
Location                        488
Temperature                     457
Vibration                       318
Last_Maintenance                369
Condition_Score                 470
Resource_Utilization            464
Delivery_Efficiency             460
Downtime_Hours                  381
Inventory_Level                   3
Logistics_Cost                  500
Timestamp                       500
SupplyChain_Efficiency_Label      3
dtype: int64

In [106]:
for col in df.columns:
    print(f"{col} : {df[col].nunique()}")

Asset_ID : 500
Location : 488
Temperature : 457
Vibration : 318
Last_Maintenance : 369
Condition_Score : 470
Resource_Utilization : 464
Delivery_Efficiency : 460
Downtime_Hours : 381
Inventory_Level : 3
Logistics_Cost : 500
Timestamp : 500
SupplyChain_Efficiency_Label : 3

In [107]:
# mapping = {'Low': 0, 'Medium': 1, 'High': 2}
# df['Inventory_Level'] = df['Inventory_Level'].map(mapping)

In [108]:
numeric_df = df.select_dtypes('number')
numeric_df.head()

,Temperature,Vibration,Condition_Score,Resource_Utilization,Delivery_Efficiency,Downtime_Hours,Logistics_Cost,SupplyChain_Efficiency_Label
0,32.34,3.99,67.39,87.04,79.99,3.22,5148.45,0
1,25.99,0.80,76.44,81.06,92.07,2.89,4454.82,1
2,31.45,4.75,61.85,79.64,88.15,1.65,3977.16,1
3,26.55,4.37,63.60,79.88,72.63,8.07,3248.65,0
4,41.66,1.43,61.62,65.99,74.93,1.83,3121.08,0

In [109]:
category_df = df.select_dtypes('str')
category_df.head()

,Asset_ID,Location,Last_Maintenance,Inventory_Level,Timestamp
0,A0001,Lake Davidland,2023-09-28,Medium,2024-09-13 19:31:26
1,A0002,West Andrew,2023-04-26,Low,2023-09-17 22:20:17
2,A0003,New Kimberlyhaven,2024-12-23,High,2024-09-08 19:32:27
3,A0004,Lake Cathyside,2024-10-22,Low,2023-10-28 06:48:55
4,A0005,South Justin,2024-08-17,High,2023-10-06 05:02:02